// <auto-generated />
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231011144932_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.RoleModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        });
                });

            modelBuilder.Entity("Core.Models.RoleUserModel", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("RoleUser");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            UserId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            UserId = 2
                        },
                        new
                        {
                            RoleId = 4,
                            UserId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            UserId = 4
                        },
                        new
                        {
                            RoleId = 4,
                            UserId = 4
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 5
                        },
                        new
                        {
                            RoleId = 3,
                            UserId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            UserId = 6
                        },
                        new
                        {
                            RoleId = 3,
                            UserId = 7
                        },
                        new
                        {
                            RoleId = 4,
                            UserId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            UserId = 8
                        },
                        new
                        {
                            RoleId = 4,
                            UserId = 8
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            UserId = 9
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            UserId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            UserId = 11
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 12
                        },
                        new
                        {
                            RoleId = 1,
                            UserId = 12
                        },
                        new
                        {
                            RoleId = 1,
                            UserId = 13
                        },
                        new
                        {
                            RoleId = 1,
                            UserId = 14
                        },
                        new
                        {
                            RoleId = 4,
                            UserId = 14
                        },
                        new
                        {
                            RoleId = 3,
                            UserId = 15
                        },
                        new
                        {
                            RoleId = 1,
                            UserId = 16
                        },
                        new
                        {
                            RoleId = 1,
                            UserId = 17
                        },
                        new
                        {
                            RoleId = 3,
                            UserId = 18
                        },
                        new
                        {
                            RoleId = 4,
                            UserId = 19
                        },
                        new
                        {
                            RoleId = 3,
                            UserId = 19
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 20
                        });
                });

            modelBuilder.Entity("Core.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 23,
                            Email = "user1@test.com",
                            Name = "User 1"
                        },
                        new
                        {
                            Id = 2,
                            Age = 87,
                            Email = "user2@test.com",
                            Name = "User 2"
                        },
                        new
                        {
                            Id = 3,
                            Age = 56,
                            Email = "user3@test.com",
                            Name = "User 3"
                        },
                        new
                        {
                            Id = 4,
                            Age = 59,
                            Email = "user4@test.com",
                            Name = "User 4"
                        },
                        new
                        {
                            Id = 5,
                            Age = 50,
                            Email = "user5@test.com",
                            Name = "User 5"
                        },
                        new
                        {
                            Id = 6,
                            Age = 43,
                            Email = "user6@test.com",
                            Name = "User 6"
                        },
                        new
                        {
                            Id = 7,
                            Age = 93,
                            Email = "user7@test.com",
                            Name = "User 7"
                        },
                        new
                        {
                            Id = 8,
                            Age = 87,
                            Email = "user8@test.com",
                            Name = "User 8"
                        },
                        new
                        {
                            Id = 9,
                            Age = 53,
                            Email = "user9@test.com",
                            Name = "User 9"
                        },
                        new
                        {
                            Id = 10,
                            Age = 58,
                            Email = "user10@test.com",
                            Name = "User 10"
                        },
                        new
                        {
                            Id = 11,
                            Age = 54,
                            Email = "user11@test.com",
                            Name = "User 11"
                        },
                        new
                        {
                            Id = 12,
                            Age = 97,
                            Email = "user12@test.com",
                            Name = "User 12"
                        },
                        new
                        {
                            Id = 13,
                            Age = 99,
                            Email = "user13@test.com",
                            Name = "User 13"
                        },
                        new
                        {
                            Id = 14,
                            Age = 99,
                            Email = "user14@test.com",
                            Name = "User 14"
                        },
                        new
                        {
                            Id = 15,
                            Age = 75,
                            Email = "user15@test.com",
                            Name = "User 15"
                        },
                        new
                        {
                            Id = 16,
                            Age = 66,
                            Email = "user16@test.com",
                            Name = "User 16"
                        },
                        new
                        {
                            Id = 17,
                            Age = 55,
                            Email = "user17@test.com",
                            Name = "User 17"
                        },
                        new
                        {
                            Id = 18,
                            Age = 22,
                            Email = "user18@test.com",
                            Name = "User 18"
                        },
                        new
                        {
                            Id = 19,
                            Age = 93,
                            Email = "user19@test.com",
                            Name = "User 19"
                        },
                        new
                        {
                            Id = 20,
                            Age = 92,
                            Email = "user20@test.com",
                            Name = "User 20"
                        });
                });

            modelBuilder.Entity("Core.Models.RoleUserModel", b =>
                {
                    b.HasOne("Core.Models.RoleModel", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
